### ISSUE TITLE
Make the Output look nicer

### ISSUE THREAD

**Issue by tannerplatt** [tannerplatt/BattleOpenSourceSE320#5]
Currently the output just states who is attacking, both player's health, and who wins the battle when it is over. Text needs to be added when the player uses a specific attack or if they heal, and whether or not the attack missed. There can also be basic ASCII art and spacing to make the overall output look nicer.

**Comment by ATacoDev** [comment]
I'll work on this one! If you wouldn't mind also adding some unit tests for this one that would be awesome :)

**Comment by ATacoDev** [comment]
<img width="420" alt="Screenshot 2024-04-17 at 11 32 57 AM" src="https://github.com/tannerplatt/BattleOpenSourceSE320/assets/146070033/886520ba-ddd2-48fc-a133-7fd48b85bbe3">

Here is some output I have been tinkering with. I think it's looking a lot better than when it first started :D
